<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>JavaScript Syntax: version 0.1</string>
	<key>fileTypes</key>
	<array>
		<string>ini</string>
	</array>
	<key>name</key>
	<string>SAGE INI</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-end</key>
		<dict>
			<key>match</key>
			<string>End</string>
			<key>name</key>
			<string>keyword.block.end.ini</string>
		</dict>
		<key>block-start</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.block.start.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.assign.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.module-tag.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)
\s*\b(
  Object(?&gt;Reskin)?|Draw|TransitionState|ConditionState|DefaultConditionState|WeaponSet|ArmorSet|UnitSpecificSounds|Body|Behavior|Prerequisites
)\b
(?:\s*(=)\s*[a-zA-Z0-9_]*\s*(ModuleTag[a-zA-Z0-9_]*))?
</string>
			<key>name</key>
			<string>meta.block.start.ini</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>match</key>
			<string>(;|//).*$\n?</string>
			<key>name</key>
			<string>comment.line.ini</string>
		</dict>
		<key>key-value</key>
		<dict>
			<key>begin</key>
			<string>([^;\n]*)(=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.assign.ini</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n|(?=;|//)</string>
			<key>name</key>
			<string>meta.key-value.ini</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\-?\b((?&gt;[0-9]?\.)?[0-9]+)(%|f)?</string>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Yes|No|None|NoSound)\b</string>
					<key>name</key>
					<string>constant.yes-no.ini</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(
  DETONATED|CRUSHED|SPLATTED|EXPLODED|
  NORMAL|BURNED|POISONED|POISONED_BETA|POISONED_GAMMA|SUICIDED|
  LASERED|FLOODED|TOPPLED|
  EXTRA_2|EXTRA_3|EXTRA_4|EXTRA_5|EXTRA_6|EXTRA_7|EXTRA_8
)\b
</string>
					<key>name</key>
					<string>constant.deathtype.ini</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(
  DEFAULT|STATUS|KILL_GARRISONED|EXPLOSION|CRUSH|ARMOR_PIERCING|SMALL_ARMS|GATTLING|RADIATION|FLAME|LASER|SNIPER|POISON|HEALING|UNRESISTABLE|WATER|DEPLOY|SURRENDER|HACK|KILL_PILOT|PENALTY|FALLING|MELEE|DISARM|HAZARD_CLEANUP|INFANTRY_MISSILE|AURORA_BOMB|LAND_MINE|JET_MISSILES|STEALTHJET_MISSILES|MOLOTOV_COCKTAIL|COMANCHE_VULCAN|SUBDUAL_MISSILE|SUBDUAL_VEHICLE|SUBDUAL_BUILDING|PARTICLE_BEAM|MICROWAVE
)\b
</string>
					<key>name</key>
					<string>constant.damagetype.ini</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(
  FAERIE_FIRE|STATUS_RIDER8|STATUS_RIDER7|STATUS_RIDER6|STATUS_RIDER5|STATUS_RIDER4|STATUS_RIDER3|STATUS_RIDER2|STATUS_RIDER1|DEPLOYED|CAN_ATTACK|DISGUISED|BOOBY_TRAPPED|REASSIGN_PARKING|KILLING_SELF|DECK_HEIGHT_OFFSET|IS_CARBOMB|IGNORING_STEALTH|NO_ATTACK_FROM_AI|IS_AIMING_WEAPON|USING_ABILITY|IS_ATTACKING|MASKED|RECONSTRUCTING|UNDERGOING_REPAIR|SOLD|CAN_STEALTH|DETECTED|STEALTHED|IS_BRAKING|IS_FIRING_WEAPON|WETAFLAME|HIJACKED|REPULSOR|PARACHUTING|AIRBORNE_TARGET|NO_ATTACK|NO_COLLISIONS|UNSELECTABLE|UNDER_CONSTRUCTION|DESTROYED
)\b
</string>
					<key>name</key>
					<string>constant.status.ini</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(
  PRELOAD|
  STRUCTURE|INFANTRY|VEHICLE|
  BLAST_CRATER|BOOBY_TRAP|AIRCRAFT_CARRIER|TECH_BASE_DEFENSE|CONSERVATIVE_BUILDING|DEMOTRAP|ARMOR_SALVAGER|WEAPON_SALVAGER|SALVAGER|HERO|DISGUISER|SUPPLY_SOURCE|HULK|BOAT|PARACHUTE|PARACHUTABLE|BALLISTIC_MISSILE|SMALL_MISSILE|DRONE|TECH_BUILDING|DEFENSIVE_WALL|PORTABLE_STRUCTURE|MINE|CRATE|HEAL_PAD|REPAIR_PAD|PROJECTILE|BRIDGE_TOWER|LANDMARK_BRIDGE|BRIDGE|TRANSPORT|COMMANDCENTER|HARVESTER|DOZER|HUGE_VEHICLE|AIRCRAFT|VEHICLE|INFANTRY|STRUCTURE|SHRUBBERY|OBSTACLE|CASH_GENERATOR|MONEY_HACKER|CLIFF_JUMPER|
  FS_AIRFIELD|FS_WARFACTORY|FS_BARRACKS|FS_ADVANCED_TECH|FS_INTERNET_CENTER|FS_FAKE|FS_STRATEGY_CENTER|FS_SUPPLY_CENTER|FS_BLACK_MARKET|FS_SUPERWEAPON|FS_SUPPLY_DROPZONE|FS_TECHNOLOGY|FS_BASE_DEFENSE|FS_FACTORY|FS_POWER|
  SELECTABLE|IMMOBILE|INERT|CAPTURABLE|POWERED|CAN_ATTACK|SCORE|IMMUNE_TO_CAPTURE|EMP_HARDENED|GARRISONABLE_UNTIL_DESTROYED|FORCEATTACKABLE|UNATTACKABLE|
  CLICK_THROUGH|ATTACK_NEEDS_LINE_OF_SIGHT|IGNORED_IN_GUI|CAN_CAST_REFLECTIONS|PRODUCED_AT_HELIPAD|CANNOT_RETALIATE|CAN_RAPPEL|SHOW_PORTRAIT_WHEN_CONTROLLED|WALK_ON_TOP_OF_WALL|
  SPAWNS_ARE_THE_WEAPONS|NO_GARRISON|IGNORES_SELECT_ALL|STEALTH_GARRISON|DONT_AUTO_CRUSH_INFANTRY|NO_SELECT|NO_HEAL_ICON|CAN_BE_REPULSED|
  MP_COUNT_FOR_VICTORY|AUTO_RALLYPOINT|CASH_GENERATOR|CANNOT_BUILD_NEAR_SUPPLIES|STICK_TO_TERRAIN_SLOPE|REVEAL_TO_ALL|SUPPLY_SOURCE_ON_PREVIEW|CAN_SEE_THROUGH_STRUCTURE|MOB_NEXUS|SCORE_DESTROY|SCORE_CREATE|REBUILD_HOLE|CLEANUP_HAZARD|ALWAYS_VISIBLE|CLEARED_BY_BUILD|NO_COLLIDE|LINEBUILD|WAVE_EFFECT|WAVEGUIDE|
  IGNORE_DOCKING_BONES|LOW_OVERLAPPABLE|AIRCRAFT_PATH_AROUND|DRAWABLE_ONLY|REVEALS_ENEMY_PATHS|REJECT_UNMANNED|OPTIMIZED_TREE|PROP
)\b
</string>
					<key>name</key>
					<string>constant.kindof.ini</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(
  PRIMARY|SECONDARY|TERTIARY|
  INVALID|UNIT|NOT_ON_RADAR|LOCAL_UNIT_ONLY|
  ALLIES|ENEMIES|NEUTRALS|NOT_SIMILAR|NOT_AIRBORNE|SUICIDE|SELF|
  ENEMIES|STRUCTURES|WALLS|SHRUBBERY|
  PLAYER_UPGRADE|DRONE_SPOTTING|HEROIC|
  NONE|ALL|DAMAGED|REALLYDAMAGED|RUBBLE|
  NIGHT|SNOW|MOVING|ATTACKING|SMOLDERING|AFLAME|
  USING_WEAPON_[ABC]|PREATTACK_[ABC]|FIRING_[ABC]|BETWEEN_FIRING_SHOTS_[ABC]|RELOADING_[ABC]|
  RAPPELLING|CLIMBING|UNPACKING|PACKING|SPECIAL_CHEERING|CARRYING|
  PANICKING|DYING|RAISING_FLAG|PARACHUTING|EXPLODED_BOUNCING|EXPLODED_FLAILING|TURRET_ROTATE|OVER_WATER|FREEFALL|
  VETERAN|ELITE|HERO|WEAPONSET_PLAYER_UPGRADE|WEAPONSET_CRATEUPGRADE_ONE|WEAPONSET_CRATEUPGRADE_TWO|WEAPONSET_VETERAN|WEAPONSET_ELITE|WEAPONSET_HERO|ARMORSET_CRATEUPGRADE_ONE|ARMORSET_CRATEUPGRADE_TWO|POWER_PLANT_UPGRADING|POWER_PLANT_UPGRADED|RADAR_EXTENDING|RADAR_UPGRADED|
  RIDERS_ATTACKING|RIDER[1-8]|DOOR_[1-4]_WAITING_OPEN|DOOR_[1-4]_OPENING|DOOR_[1-4]_WAITING_TO_CLOSE|DOOR_[1-4]_CLOSING|AWAITING_CONSTRUCTION|ACTIVELY_CONSTRUCTING|PARTIALLY_CONSTRUCTED|ACTIVELY_BEING_CONSTRUCTED|CONSTRUCTION_COMPLETE|SOLD|JAMMED|RIGHT_TO_CENTER|CENTER_TO_RIGHT|LEFT_TO_CENTER|CENTER_TO_LEFT|GARRISONED|SECOND_LIFE|PREORDER|CAPTURED|JETEXHAUST|JETAFTERBURNER|LOADED|POST_COLLAPSE|ENEMYNEAR|SPECIAL_DAMAGED|BACKCRUSHED|FRONTCRUSHED|USER_[1-2]|
  ONCE|ONCE_BACKWARDS|LOOP|LOOP_BACKWARDS|MANUAL|
  START_FRAME_FIRST|START_FRAME_LAST|RANDOMSTART|PRISTINE_BONE_POS_IN_FINAL_FRAME|
  ADJUST_HEIGHT_BY_CONSTRUCTION_PERCENT|MAINTAIN_FRAME_ACROSS_STATES|MAINTAIN_FRAME_ACROSS_STATES[2-3]|
  DOWN_DEFAULT|UP_DAY|UP_NIGHT|UP_SNOW|UP_SNOWNIGHT|
  PER_ATTACK|PER_CLIP|PER_SHOT|
  DAMAGE|RATE_OF_FIRE|RANGE|
  CONTINUOUS_FIRE_SLOW|CONTINUOUS_FIRE_MEAN|CONTINUOUS_FIRE_FAST|
  DISABLED_HELD|DISABLED_UNDERPOWERED|
  BOX|Box|CYLINDER|Cylinder|SPHERE|Sphere|
  SHADOW_VOLUME|
  MISC_MAN_MADE|MISC_NATURAL|
  CREATE_ABOVE_LOCATION|CREATE_AT_LOCATION|CREATE_AT_EDGE_FARTHEST_FROM_TARGET|CREATE_AT_EDGE_NEAR_TARGET|CREATE_AT_EDGE_FARTHEST_FROM_SOURCE|CREATE_AT_EDGE_NEAR_SOURCE|USE_OWNER_OBJECT|
  PLACED_BY_PLAYER|
  RETURN_TO_BASE|
  INITIAL|MIDPOINT|FINAL|
  SET_NORMAL|SET_NORMAL_UPGRADED|SET_PANIC|SET_TAXIING|
  Stealthed|ATTACK_BUILDINGS|
  TAKING_DAMAGE
)\b
</string>
					<key>name</key>
					<string>constant.other.ini</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key-value</string>
				</dict>
			</array>
		</dict>
		<key>object-block</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Object|Weapon|ParticleSystem|ObjectCreationList|FXList)\b\s*([^;\n]*)</string>
			<key>name</key>
			<string>meta.block.object.ini</string>
		</dict>
		<key>special-block</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.block.start.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Turret)\b(?!\s*=)</string>
			<key>name</key>
			<string>meta.block.special.ini</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ini</string>
	<key>uuid</key>
	<string>93E017CC-6F27-11D9-90EB-000D93589AF8</string>
</dict>
</plist>
